sudo: false 
language: sh

# Caching so the next build will be fast too.
cache:
  directories:
  - $HOME/.stack
  - $TRAVIS_BUILD_DIR/.stack-work

# The different configurations we want to test.
matrix:
  # Build with different GHC versions and stable package sets
  include:
  - env: RESOLVER=lts-12
    compiler: "LTS12"
    deploy:
      provider: releases
      api_key: "e1bfc7517ac37152ab8633427701c62acadb52cc"
      file: "hastile.zip"
      skip_cleanup: true
      on:
        tags: true
  - env: RESOLVER=lts-12
    compiler: "LTS12"
    os: osx

  - env: RESOLVER=lts-12
    compiler: "LTS12"
    os: windows

before_install:
- if [[ $TRAVIS_OS_NAME == 'windows' ]]; then choco install haskell-stack; else curl -sSL https://get.haskellstack.org/ | sh; fi

install:
- stack setup --stack-yaml stack-ci.yaml --no-system-ghc --no-terminal -j2 --resolver $RESOLVER
- stack build --copy-bins --local-bin-path . --stack-yaml stack-ci.yaml --no-system-ghc --no-terminal -j2 --haddock --no-haddock-deps --resolver $RESOLVER
- zip hastile.zip hastile migrate 
