sudo: false 
language: generic

# Caching so the next build will be fast too.
cache:
  directories:
  - $HOME/.stack
  - $TRAVIS_BUILD_DIR/.stack-work

# The different configurations we want to test.
matrix:
  # Build with different GHC versions and stable package sets
  include:
  - env: RESOLVER=lts-12
    compiler: "LTS12"

  - env: RESOLVER=lts-12
    compiler: "LTS12"
    os: osx

  - env: RESOLVER=lts-12
    compiler: "LTS12"
    os: windows

before_install:
- if [[ $TRAVIS_OS_NAME == 'windows' ]]; then choco install haskell-stack; else curl -sSL https://get.haskellstack.org/ | sh; fi

install:
- stack setup --stack-yaml stack-ci.yaml --no-system-ghc --no-terminal -j2 --resolver $RESOLVER
- stack build --stack-yaml stack-ci.yaml --no-system-ghc --no-terminal -j2 --haddock --no-haddock-deps --resolver $RESOLVER
