name: CI

on: [push, pull_request]

jobs:
  build_linux:
    runs-on: ubuntu-latest    

    steps:
    - name: Install Postgresql 11 and PostGIS
      uses: huaxk/postgis-action@v1
      with:
        postgresql version: '11'
        postgresql password: 'password'
        postgresql user: 'hastile' 
        postgresql db: 'hastile_test'

    - name: Get code
      uses: actions/checkout@v2
      with:
        path: ./hastile

    - name: Checkout zellige repo
      uses: actions/checkout@v2
      with:
        repository: zellige/zellige
        path: ./zellige
    
    - name: Setup Stack
      uses: mstksg/setup-stack@v2
    
    - name: Cache Stack downloads
      uses: actions/cache@v1
      env:
        cache-name: cache-stack-modules-linux
      with:
        path: /home/runner/.stack/
        key: ${{ hashFiles('**/stack.yaml.lock') }}

    - name: Cache Stack Build
      uses: actions/cache@v1
      env:
        cache-name: cache-stack-local-modules-linux
      with:
        path: ./hastile/.stack/
        key: ${{ hashFiles('**/hastile.cabal') }}${{ hashFiles('**/stack.yaml.lock') }}
    
    - name: stack pre (setup, configure)
      run: |
        stack setup --stack-yaml stack-ci.yaml --no-terminal -j2
        stack build --stack-yaml stack-ci.yaml --no-system-ghc --only-configure --no-terminal -j2
      working-directory: ./hastile

    - name: stack compile and install
      run: |
        stack build  --stack-yaml stack-ci.yaml --no-terminal -j2
        stack install  --stack-yaml stack-ci.yaml --no-terminal -j2
      working-directory: ./hastile

    - name: db migrate
      run: |
        ./db/migration setup --stack test
      working-directory: ./hastile
    
    - name: stack test
      run: |
        stack test  --stack-yaml stack-ci.yaml --no-terminal -j2
      working-directory: ./hastile

  build_windows:
    runs-on: windows-latest

    steps:

    - name: Install Postgresql 11 Client
      run: choco install postgresql11

    - name: Get code
      uses: actions/checkout@v2
      with:
        path: ./hastile

    - name: Checkout zellige repo
      uses: actions/checkout@v2
      with:
        repository: zellige/zellige
        path: ./zellige
    
    - name: Setup Stack
      uses: mstksg/setup-stack@v2
    
    - name: Cache Stack downloads
      uses: actions/cache@v1
      env:
        cache-name: cache-stack-modules-windows
      with:
        path: /home/runner/.stack/
        key: ${{ hashFiles('**/stack.yaml.lock') }}

    - name: Cache Stack Build
      uses: actions/cache@v1
      env:
        cache-name: cache-stack-local-modules-windows
      with:
        path: ./hastile/.stack/
        key: ${{ hashFiles('**/hastile.cabal') }}${{ hashFiles('**/stack.yaml.lock') }}
      
    - name: stack pre (setup, configure)
      run: |
        stack setup --stack-yaml stack-ci.yaml --no-terminal -j2
        stack build --stack-yaml stack-ci.yaml --no-system-ghc --only-configure --no-terminal -j2
      working-directory: ./hastile

    - name: stack compile
      run: |
        stack build  --stack-yaml stack-ci.yaml --no-terminal -j2
      working-directory: ./hastile        