name: CI

on: [push, pull_request]

jobs:
  build_linux:
    runs-on: ubuntu-latest    

    steps:
    - name: Install Postgresql 11 and PostGIS
      uses: huaxk/postgis-action@v1
      with:
        postgresql version: '11'
        postgresql password: 'password'
        postgresql user: 'hastile' 
        postgresql db: 'hastile_test'

    - name: Get code
      uses: actions/checkout@v2
      with:
        path: ./hastile

    - name: Checkout zellige repo
      uses: actions/checkout@v2
      with:
        repository: zellige/zellige
        path: ./zellige
    
    - name: Setup Stack
      uses: mstksg/setup-stack@v2
    
    - name: Cache Stack downloads
      uses: actions/cache@v1
      env:
        cache-name: cache-stack-modules-linux
      with:
        path: /home/runner/.stack/
        key: ${{ hashFiles('**/stack.yaml.lock') }}

    - name: Cache Stack Build
      uses: actions/cache@v1
      env:
        cache-name: cache-stack-local-modules-linux
      with:
        path: ./hastile/.stack/
        key: ${{ hashFiles('**/hastile.cabal') }}${{ hashFiles('**/stack.yaml.lock') }}
      
    - name: stack install, build and test
      run: |
        stack build
        stack test
      working-directory: ./hastile

  build_windows:
    runs-on: windows-latest

    steps:

    - name: Get code
      uses: actions/checkout@v2
      with:
        path: ./hastile

    - name: Checkout zellige repo
      uses: actions/checkout@v2
      with:
        repository: zellige/zellige
        path: ./zellige
    
    - name: Setup Stack
      uses: mstksg/setup-stack@v2
    
    - name: Cache Stack downloads
      uses: actions/cache@v1
      env:
        cache-name: cache-stack-modules-windows
      with:
        path: /home/runner/.stack/
        key: ${{ hashFiles('**/stack.yaml.lock') }}

    - name: Cache Stack Build
      uses: actions/cache@v1
      env:
        cache-name: cache-stack-local-modules-windows
      with:
        path: ./hastile/.stack/
        key: ${{ hashFiles('**/hastile.cabal') }}${{ hashFiles('**/stack.yaml.lock') }}
      
    - name: stack install, build and test
      run: |
        stack build
      working-directory: ./hastile
        